/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.paquete;

/**
 *
 * @author Isaias
 */
import Controls.AlojamientoData;
import Controls.ClienteData;
import Controls.Conexion;
import Controls.DestinoData;
import Controls.ExtraalojamientoData;
import Controls.PaqueteData;
import Controls.TransporteData;
import Models.Alojamiento;
import Models.Destino;
import Models.Extraalojamiento;
import Models.Transporte;
import Models.Paquete;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

public class editarEliminarPaquete extends javax.swing.JInternalFrame {
    Conexion con = new Conexion();

    ClienteData cd = new ClienteData(con);

    DestinoData dd = new DestinoData(con);

    TransporteData td = new TransporteData(con);

    AlojamientoData ad = new AlojamientoData(con);

    ExtraalojamientoData ed = new ExtraalojamientoData(con);

    PaqueteData pd = new PaqueteData(con);
    /**
     * Creates new form editarEliminarPaquete
     */
    public editarEliminarPaquete() {
        initComponents();
        llenarComboPaquete();
        limpiarCampos();
        completarFecha();
    }
    public void completarFecha(){
        LocalDate a = LocalDate.now();
        jTextEmision.setText(a.toString());
    }
    public void llenarComboPaquete() {
        ArrayList<Paquete> listapaquete = (ArrayList<Paquete>) pd.listarTodosLosPaquetes();

        for (Paquete p : listapaquete) {
            jComboPaquete.addItem(p);
        }
        jComboPaquete.setSelectedIndex(-1);
    }
    public void limpiarCampos(){
        jComboPaquete.setSelectedIndex(-1);
        jComboDestino.setSelectedIndex(-1);
        jComboTransporte.setSelectedIndex(-1);
        jComboAlojamiento.setSelectedIndex(-1);
        jComboExtra.setSelectedIndex(-1);
        jFechaInicio.setDate(null);
        jFechaFin.setDate(null);
        jSpinnercantidad.setValue(Integer.valueOf(0));
        jTextEmision.setText("");
        buttonGroup1.clearSelection();
        jTextCostoTotal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboPaquete = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboExtra = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextCostoTotal = new javax.swing.JTextField();
        jFechaInicio = new com.toedter.calendar.JDateChooser();
        jFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jBtGuardar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jRadioSi = new javax.swing.JRadioButton();
        jRadioNo = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jComboTransporte = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSpinnercantidad = new javax.swing.JSpinner();
        jBtCalcular = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboDestino = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboAlojamiento = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jTextEmision = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Paquete Turistico");
        setPreferredSize(new java.awt.Dimension(674, 560));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Editar Paquete");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Paquete:");

        jComboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPaqueteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad de Personas:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Transporte:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Extra:");

        jComboExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboExtraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Inicio:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha fin:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Fecha emisión:");

        jTextCostoTotal.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Costo total:");

        jBtGuardar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtGuardar.setText("Guardar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jBtSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtSalir.setText("Salir");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSi);
        jRadioSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioSi.setText("Si");

        buttonGroup1.add(jRadioNo);
        jRadioNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioNo.setText("No");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Activo:");

        jComboTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboTransporteMouseClicked(evt);
            }
        });

        jBtCalcular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtCalcular.setText("Calcular");
        jBtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCalcularActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Destino:");

        jComboDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboDestinoFocusLost(evt);
            }
        });
        jComboDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboDestinoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboDestinoMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Alojamiento:");

        jComboAlojamiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboAlojamientoFocusLost(evt);
            }
        });

        jTextEmision.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jComboPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(201, 201, 201))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(89, 89, 89)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioSi)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioNo))
                                    .addComponent(jFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtGuardar)
                                .addGap(27, 27, 27)
                                .addComponent(jBtCalcular)
                                .addGap(27, 27, 27)
                                .addComponent(jBtSalir)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboDestino, 0, 200, Short.MAX_VALUE)
                            .addComponent(jComboTransporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(317, 317, 317)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinnercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboAlojamiento, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jComboExtra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jRadioSi)
                            .addComponent(jRadioNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtCalcular)
                    .addComponent(jBtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboExtraActionPerformed

    private void jComboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPaqueteActionPerformed
        jComboDestino.removeAllItems();
        jComboTransporte.removeAllItems();
        jComboAlojamiento.removeAllItems();
        jComboExtra.removeAllItems();
        Paquete p = (Paquete) jComboPaquete.getSelectedItem();
        
        if (jComboPaquete.getSelectedIndex() != -1 || jComboPaquete.getSelectedItem() != null){
        jComboDestino.addItem((Destino)p.getExtra().getAlojamiento().getDestino());
        jComboDestino.setSelectedIndex(0);
        jComboTransporte.addItem((Transporte)p.getTransporte());
        jComboTransporte.setSelectedIndex(0);
        jComboAlojamiento.addItem((Alojamiento)p.getExtra().getAlojamiento());
        jComboAlojamiento.setSelectedIndex(0);
        jComboExtra.addItem((Extraalojamiento)p.getExtra());
        jComboExtra.setSelectedIndex(0);
        //Fechas
        LocalDate localdateemision = LocalDate.now();
        Date d = java.sql.Date.valueOf(p.getFechaInicio());
         jFechaInicio.setDate(d);
        Date de = java.sql.Date.valueOf(p.getFechaFin());
         jFechaFin.setDate(de);
        
        //Activo
        if (p.isActivo()) {
                jRadioSi.setSelected(true);
            } else {
                jRadioNo.setSelected(true);
            }
        }
    }//GEN-LAST:event_jComboPaqueteActionPerformed

    private void jBtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCalcularActionPerformed
        Paquete p = (Paquete) jComboPaquete.getSelectedItem();
        
        LocalDate localdateInicio = jFechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localdateFin = jFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        p.setTransporte((Transporte) jComboTransporte.getSelectedItem());
        p.setExtra((Extraalojamiento) jComboExtra.getSelectedItem());

        p.setFechaInicio(localdateInicio);
        p.setFechaFin(localdateFin);
        Integer valor = (Integer) jSpinnercantidad.getValue();
        if (valor <= 0) {
            JOptionPane.showMessageDialog(this, "No selecciono la cantidad de personas.");
        } else {
            Float a =(Float)p.getCostoTotalPaquete() * valor;
            if (a <= 0) {
                JOptionPane.showMessageDialog(this, "Error en las fechas de inicio/fin.");
            } else {
                jTextCostoTotal.setText(a.toString());
            }
        }

        p.setActivo(true);
    }//GEN-LAST:event_jBtCalcularActionPerformed

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
        Paquete p = (Paquete) jComboPaquete.getSelectedItem();
        LocalDate localdateInicio = jFechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localdateFin = jFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localdateemision = LocalDate.now();
                
        p.setCliente(p.getCliente());
        p.setTransporte((Transporte) jComboTransporte.getSelectedItem());
        p.setExtra((Extraalojamiento) jComboExtra.getSelectedItem());

        p.setFechaInicio(localdateInicio);
        p.setFechaFin(localdateFin);
        p.setFechaEmisionPaquete(localdateemision);
        p.setCostoTotalPaquete(p.getCostoTotalPaquete() * ((Integer) jSpinnercantidad.getValue()));

        int personas = (int) jSpinnercantidad.getValue();
        
        p.setCant(personas);
        
        if (jRadioSi.isSelected()) {
            p.setActivo(true);
        } else {
            p.setActivo(false);
        }

        pd.editarPaquete(p);
        limpiarCampos();
        completarFecha();
    }//GEN-LAST:event_jBtGuardarActionPerformed

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jBtSalirActionPerformed

    private void jComboDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboDestinoMouseClicked
        jComboDestino.removeAllItems();    
        ArrayList<Destino> listadestinos = (ArrayList<Destino>) dd.listarDestinosActivos();

        for (Destino d : listadestinos) {
            jComboDestino.addItem(d);
        }
        jComboTransporte.removeAllItems();
        jComboAlojamiento.removeAllItems();
        jComboExtra.removeAllItems();
    }//GEN-LAST:event_jComboDestinoMouseClicked

    private void jComboDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboDestinoFocusLost

        Destino d = (Destino) jComboDestino.getSelectedItem();

        ArrayList<Transporte> listaTransporte = (ArrayList<Transporte>) td.listarTransportesDeUnDestino(d.getIdDestino());

        for (Transporte t : listaTransporte) {
            jComboTransporte.addItem(t);
        }
            jComboTransporte.setSelectedIndex(-1);
        
        ArrayList<Alojamiento> listaalojamientos = (ArrayList<Alojamiento>) ad.listarAlojamientosDeUnDestino(d.getIdDestino());

        for (Alojamiento a : listaalojamientos) {
            jComboAlojamiento.addItem(a);
        }
        jComboAlojamiento.setSelectedIndex(-1);
    }//GEN-LAST:event_jComboDestinoFocusLost

    private void jComboAlojamientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboAlojamientoFocusLost
        Alojamiento a = (Alojamiento) jComboAlojamiento.getSelectedItem();

        ArrayList<Extraalojamiento> listaExtra = (ArrayList<Extraalojamiento>) ed.listarExtrasDeUnAlojamiento(a.getIdAlojamiento());

        for (Extraalojamiento e : listaExtra) {
            jComboExtra.addItem(e);
        }
        jComboExtra.setSelectedIndex(-1);
    }//GEN-LAST:event_jComboAlojamientoFocusLost

    private void jComboDestinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboDestinoMouseReleased

    }//GEN-LAST:event_jComboDestinoMouseReleased

    private void jComboTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboTransporteMouseClicked

    }//GEN-LAST:event_jComboTransporteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtCalcular;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JButton jBtSalir;
    private javax.swing.JComboBox<Alojamiento> jComboAlojamiento;
    private javax.swing.JComboBox<Destino> jComboDestino;
    private javax.swing.JComboBox<Extraalojamiento> jComboExtra;
    private javax.swing.JComboBox<Paquete> jComboPaquete;
    private javax.swing.JComboBox<Transporte> jComboTransporte;
    private com.toedter.calendar.JDateChooser jFechaFin;
    private com.toedter.calendar.JDateChooser jFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioNo;
    private javax.swing.JRadioButton jRadioSi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnercantidad;
    private javax.swing.JTextField jTextCostoTotal;
    private javax.swing.JTextField jTextEmision;
    // End of variables declaration//GEN-END:variables

}

