/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.extraalojamiento;

import Controls.AlojamientoData;
import Controls.Conexion;
import Controls.ExtraalojamientoData;
import Models.Alojamiento;
import Models.Extraalojamiento;
import java.util.ArrayList;

/**
 *
 * @author Isaias
 */
public class editarEliminarExtra extends javax.swing.JInternalFrame {
    Conexion con = new Conexion();

    AlojamientoData ad = new AlojamientoData(con);

    ExtraalojamientoData ed = new ExtraalojamientoData(con);
    /**
     * Creates new form editarEliminarExtra
     */
    public editarEliminarExtra() {
        initComponents();
        llenarComboExtra();
        limpiarCampos();
    }
    public void limpiarCampos(){
        jComboExtra.setSelectedIndex(-1);
        jComboMenu.setSelectedIndex(-1);
        jTextCosto.setText("");
        buttonGroup1.clearSelection();
    }
    public void llenarComboExtra() {
        ArrayList<Extraalojamiento> listaExtraalojamiento = (ArrayList<Extraalojamiento>) ed.listarTodosLosExtras();

        for (Extraalojamiento e : listaExtraalojamiento) {
            jComboExtra.addItem(e);
        }
        jComboExtra.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioSi = new javax.swing.JRadioButton();
        jRadioNo = new javax.swing.JRadioButton();
        jComboExtra = new javax.swing.JComboBox<>();
        jComboMenu = new javax.swing.JComboBox<>();
        jTextCosto = new javax.swing.JTextField();
        jBtGuardar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Extra");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Editar Extra");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Extra:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Menu:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Costo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Activo:");

        buttonGroup1.add(jRadioSi);
        jRadioSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioSi.setText("Si");

        buttonGroup1.add(jRadioNo);
        jRadioNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioNo.setText("No");

        jComboExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboExtraActionPerformed(evt);
            }
        });

        jComboMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desayuno", "Media pension + Desayuno", "Pension completa + Desayuno" }));
        jComboMenu.setSelectedIndex(-1);

        jBtGuardar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtGuardar.setText("Guardar");
        jBtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGuardarActionPerformed(evt);
            }
        });

        jBtSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBtSalir.setText("Salir");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addComponent(jComboExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioSi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioNo))
                        .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboMenu, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jBtGuardar)))
                        .addGap(30, 30, 30)
                        .addComponent(jBtSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioSi)
                    .addComponent(jRadioNo))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtSalir))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboExtraActionPerformed
         Extraalojamiento e = (Extraalojamiento) jComboExtra.getSelectedItem();

        if (jComboExtra.getSelectedItem() != null || jComboExtra.getSelectedIndex() != -1) {
            jComboMenu.setSelectedItem(e.getTipoDeMenu());
            jTextCosto.setText(Float.toString(e.getCosto()));
            if (e.isActivo()) {
                jRadioSi.setSelected(true);
            } else {
                jRadioNo.setSelected(true);
            }
        }

    }//GEN-LAST:event_jComboExtraActionPerformed

    private void jBtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGuardarActionPerformed
        Extraalojamiento e = (Extraalojamiento) jComboExtra.getSelectedItem();
        
        e.setAlojamiento(e.getAlojamiento());
        e.setTipoDeMenu(jComboMenu.getSelectedItem().toString());
        e.setCosto(Float.parseFloat(jTextCosto.getText()));
        if (jRadioSi.isSelected()) {
            e.setActivo(true);
        } else {
            e.setActivo(false);
        }

        ed.editarExtra(e);

        limpiarCampos();
    }//GEN-LAST:event_jBtGuardarActionPerformed

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtGuardar;
    private javax.swing.JButton jBtSalir;
    private javax.swing.JComboBox<Extraalojamiento> jComboExtra;
    private javax.swing.JComboBox<String> jComboMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioNo;
    private javax.swing.JRadioButton jRadioSi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCosto;
    // End of variables declaration//GEN-END:variables
}
